export { Banner } from "./banner/Banner";
export { Description } from "./description/Description";
export { Programs } from "./programs/Programs";
export { Ticker } from "./ticker/Ticker";
export { Teachers } from "./teachers/Teachers";
export { For } from "./for/For";
export { WorkShops } from "./workshops/WorkShops";
export { WhyUs } from "./whyus/WhyUs";
export { Graduates } from "./graduates/Graduates";
